version: '3.8'

services:
  database:
    container_name: dreamrooms-sql-server
    ports:
      - 1433:1433
    build:
      context: .
      dockerfile: Database_Dockerfile
    volumes:
      - dreamrooms-volume:/var/opt/mssql
    networks:
      - dreamrooms-network

  application:
    container_name: dreamrooms-application
    ports:
      - 5001:80
      - 5000:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
      - ASPNETCORE_HTTPS_PORTS=5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=CertPassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/dreamrooms.pfx
      - ConnectionStrings:Default=Server=dreamrooms-sql-server,1433;Database=DreamRoomsDb;User Id=sa;Password=-Test123-;Encrypt=False;
    build:
      context: .
      dockerfile: App_Dockerfile
    networks:
      - dreamrooms-network
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https
    depends_on:
      - database

networks:
  dreamrooms-network:
    driver: bridge

volumes:
  dreamrooms-volume:
