version: '3.8'

services:
  application:
    container_name: dreamrooms-application
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:Default=Server=dreamrooms-sql-server,1433;Database=DreamRoomsDb;User Id=sa;Password=-Test123-;Encrypt=False;
    build:
      context: .
      dockerfile: App_Dockerfile
    networks:
      - dreamrooms-network

  database:
    container_name: dreamrooms-sql-server
    ports:
      - 1433:1433
    build:
      context: .
      dockerfile: Database_Dockerfile
    volumes:
      - dreamrooms-volume:/var/opt/mssql
    networks:
      - dreamrooms-network

networks:
  dreamrooms-network:
    driver: bridge

volumes:
  dreamrooms-volume:
