version: '3.4'

name: dreamrooms-compose
services:
  api:
    image: ${DOCKER_REGISTRY-}dreamrooms_api
    container_name: dreamrooms_api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    environment:
      - ConnectionStrings__Default=Server=database,1433;Database=DreamRoomsDb;User Id=sa;Password=-Test123-;Encrypt=False;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
    ports:
      - '4000:80'
      - '5000:443'
    networks:
      - default
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  database:
    container_name: dreamrooms_database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=-Test123-
      - MSSQL_PID=Express
      - MSSQL_TCP_PORT=1433
    ports:
      - 1433:1433
    networks:
      - default
    volumes:
      - db:/var/opt/mssql

networks:
  default:
    driver: bridge

volumes:
  db:
