version: '3.8'

services:
  database:
    container_name: dreamrooms-sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=-Test123-
      - MSSQL_PID=Express
      - MSSQL_TCP_PORT=1433
    volumes:
      - dreamrooms-volume:/var/opt/mssql
    networks:
      - dreamrooms-network

networks:
  dreamrooms-network:
    driver: bridge

volumes:
  dreamrooms-volume:
