@host = https://localhost:5000

POST {{host}}/staff/receptionist
Content-Type: application/json

{
    "FirstName": "Phill",
    "LastName": "Cash",
    "Email": "phill.cache22@gmail.com",
    "PhoneNumber": "535 535 535",
    "Password": "Password123",
    "ConfirmedPassword": "Password123"
}